name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Angular app with Docker
      run: |
        docker build --tag portfoliosite --file Dockerfile .
        docker run --name portfoliosite-container portfoliosite

    - name: Copy built files from Docker container
      run: |
        mkdir -p $HOME/docs
        docker cp portfoliosite-container:/app/docs/browser $HOME/docs

  deploy:

    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        deploy_key: ${{ secrets.GH_PAGES_DEPLOY_KEY }}
        publish_dir: $HOME/docs
